### ISSUE TITLE
Rough cut! & naming question

### ISSUE THREAD

**Issue by kfrn** [amiaopensource/time-based-media-art#1]
Hi AMIA people and others, 
This repo springs off [analog-inspection](https://github.com/amiaopensource/analog-inspection/), as mentioned in [this](https://github.com/amiaopensource/analog-inspection/issues/11) thread.
Here, we can collect resources to do with media art/software-based art. I thought I'd get the ball rolling, but please edit and add/remove links.
A question: is **software-based-art** an appropriate title for the repo? There is a lot of crossover between media art/time-based art and software-based-art, so I'm not sure where to land. However, as it stands, many of the resources are not specifically about software-based art.

**Comment by kieranjol** [comment]
Firstly, this is a great repo! Secondly, pinging @jfarbowitz (amiaopensource contributor) as he recently co-authored something for the Guggenheim about this topic: https://www.guggenheim.org/blogs/checklist/restoring-brandon-shu-lea-cheangs-early-web-artwork

**Comment by jfarbowitz** [comment]
Thanks for thinking of me @kieranjol . Based on the resources that you put in this repo so far I think it would be more appropriate to call it "Time-Based Media Art Resources" since time-based media is the larger umbrella under which software-based art is but a small niche. Time-based media refers to any artwork that unfolds over time such as a film, video, or computer program.  

Unless you plan to focus much more specifically on only software-based art, I would stick with the "Time-Based Media" label.

There's also the question of whether the terms "software-based art" or "computer-based art" are equivalent or have different resonances. But that's a discussion for another day.

**Comment by jfarbowitz** [comment]
Oh, and don't forget [Techfocus I](http://resources.conservation-us.org/techfocus/tech-i-speakers-tw/) about video art and [Techfocus II](http://www.tate.org.uk/download/file/fid/20951) about film and slide-based art.

**Comment by kfrn** [comment]
Thanks @kieranjol & @jfarbowitz.
Name changed! I also added some more resources, including the above (cheers @jfarbowitz). Please feel free to contribute directly too.

_There's also the question of whether the terms "software-based art" or "computer-based art" are equivalent or have different resonances._
And we could also throw net art into the mix ;)

**Comment by retokromer** [comment]
I plenty agree, the title is better. Thanks you all for contributing!
